# Generated by Django 5.2.12 on 2026-04-02 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('VACATION', 'Urlaub'), ('SICK', 'Krankheit'), ('SPECIAL', 'Sonderurlaub'), ('UNPAID', 'Unbezahlter Urlaub'), ('HOLIDAY', 'Feiertag'), ('OVERTIME_COMP', 'Überstundenausgleich')], max_length=30, unique=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('deducts_from_vacation', models.BooleanField(default=False)),
                ('deducts_from_overtime', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Abwesenheitstyp',
                'verbose_name_plural': 'Abwesenheitstypen',
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('APPROVED', 'Genehmigt'), ('REJECTED', 'Abgelehnt'), ('CANCELLED', 'Storniert')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='absences.leavetype')),
            ],
            options={
                'verbose_name': 'Abwesenheitsantrag',
                'verbose_name_plural': 'Abwesenheitsanträge',
                'indexes': [models.Index(fields=['user', 'status'], name='absences_ab_user_id_160169_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='chk_absence_dates')],
            },
        ),
    ]
