# Generated by Django 5.2.12 on 2026-04-03 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_seed_leavetypes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerequest',
            name='au_eingereicht_am',
            field=models.DateField(blank=True, null=True, verbose_name='AU eingereicht am'),
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='au_vorhanden',
            field=models.BooleanField(default=False, verbose_name='AU liegt vor'),
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='type_change_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='type_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_absences', to=settings.AUTH_USER_MODEL),
        ),
    ]
