# Generated by Django 5.2.12 on 2026-04-02 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekly_work_hours', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('annual_leave_days', models.IntegerField(default=30)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Vollzeit'), ('PART_TIME', 'Teilzeit'), ('MINI_JOB', 'Minijob'), ('INTERN', 'Praktikant')], default='FULL_TIME', max_length=20)),
                ('federal_state', models.CharField(choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hessen'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thüringen')], default='BY', max_length=2)),
                ('leave_carry_over', models.BooleanField(default=True)),
                ('max_carry_over_days', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mitarbeiterprofil',
                'verbose_name_plural': 'Mitarbeiterprofile',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monday_minutes', models.IntegerField(default=480)),
                ('tuesday_minutes', models.IntegerField(default=480)),
                ('wednesday_minutes', models.IntegerField(default=480)),
                ('thursday_minutes', models.IntegerField(default=480)),
                ('friday_minutes', models.IntegerField(default=480)),
                ('saturday_minutes', models.IntegerField(default=0)),
                ('sunday_minutes', models.IntegerField(default=0)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arbeitszeitplan',
                'verbose_name_plural': 'Arbeitszeitpläne',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['user', 'effective_from'], name='accounts_wo_user_id_3a5033_idx')],
            },
        ),
    ]
