# Generated by Django 5.2.12 on 2026-04-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Abteilung'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Mitarbeiter'), ('HR', 'Personalmanagement'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=20, verbose_name='Rolle'),
        ),
    ]
