# Generated by Django 5.2.12 on 2026-04-02 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Überstundenkonto',
                'verbose_name_plural': 'Überstundenkonten',
            },
        ),
        migrations.CreateModel(
            name='OvertimeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField()),
                ('amount_minutes', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('monthly_settlement', 'Monatsabrechnung'), ('absence_deduction', 'Abwesenheitsabzug'), ('overtime_comp_deduction', 'Überstundenausgleich-Abzug'), ('manual_adjustment', 'Manuelle Anpassung'), ('year_end_carryover', 'Jahresübertrag')], max_length=30)),
                ('reference_month', models.CharField(blank=True, max_length=7)),
                ('reason', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='overtime.overtimeaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ot_transactions', to=settings.AUTH_USER_MODEL)),
                ('reference_absence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='absences.absencerequest')),
            ],
            options={
                'verbose_name': 'Überstunden-Transaktion',
                'verbose_name_plural': 'Überstunden-Transaktionen',
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference_month__gt', '')), fields=('account', 'transaction_type', 'reference_month'), name='uq_monthly_settlement')],
            },
        ),
    ]
