# Generated by Django 5.2.12 on 2026-04-02 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('break_minutes', models.IntegerField(default=0)),
                ('required_break_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Läuft'), ('PAUSED', 'Pausiert'), ('COMPLETED', 'Abgeschlossen'), ('AUTO_CLOSED', 'Automatisch geschlossen'), ('MANUAL', 'Manuell eingetragen')], default='RUNNING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('violations_json', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zeiteintrag',
                'verbose_name_plural': 'Zeiteinträge',
                'indexes': [models.Index(fields=['user', 'date'], name='timesession_user_id_6bd289_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'RUNNING')), fields=('user',), name='uq_user_running')],
            },
        ),
    ]
