# Generated by Django 5.2.12 on 2026-04-03 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('timesessions', '0002_timeentry_correction_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_entry', models.BigIntegerField()),
                ('original_date', models.DateField()),
                ('original_start_time', models.DateTimeField()),
                ('original_end_time', models.DateTimeField(blank=True, null=True)),
                ('original_break_minutes', models.IntegerField(default=0)),
                ('original_net_minutes', models.IntegerField(default=0)),
                ('deletion_reason', models.TextField()),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions_made', to=settings.AUTH_USER_MODEL)),
                ('original_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('original_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gelöschter Zeiteintrag',
                'verbose_name_plural': 'Gelöschte Zeiteinträge',
                'ordering': ['-created_at'],
            },
        ),
    ]
