# Generated by Django 5.2.12 on 2026-04-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesessions', '0003_add_deleted_time_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='pause_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
